/* Presentation owns layout only: policy, mastery and plans stay server-owned. */
'use strict';
const viewNames={study:['陪学工作台','先尝试，再求助；每次作答形成可追溯的学习证据。'],plan:['计划 · 我的学习路径','津津提出建议，路径归你所有；只有你的签署才让计划生效。'],reviews:['复习队列','按到期与遗忘风险排序；复习不提供提示，保留独立回忆证据。'],evidence:['成长证据中心','证据，不是排名；只与自己的历史比较，模型估计不是能力标签。'],collaboration:['圆桌与探究','举例、质疑、评审；候选不是结论，讲给虚拟学生听以检查自己的理解。'],settings:['设置 · 个性化中心','展示由你决定；教学规则不随偏好关闭，授权可以撤回。']};
document.body.dataset.view='study';
function updateHeading(){const visible=[...document.querySelectorAll('main>section')].find(s=>!s.hidden);const names=viewNames[visible?.id]||viewNames.study;$('view-title').textContent=names[0];$('view-description').textContent=names[1];}
const headingObserver=new MutationObserver(updateHeading);for(const panel of document.querySelectorAll('main>section'))headingObserver.observe(panel,{attributes:true,attributeFilter:['hidden']});
document.querySelectorAll('[data-shortcut]').forEach(button=>button.onclick=()=>activateTab($('tab-'+button.dataset.shortcut)));
$('toggle-left').onclick=()=>{const hidden=document.body.classList.toggle('no-left');$('toggle-left').setAttribute('aria-expanded',String(!hidden));};
$('compact-mode').onchange=()=>document.body.classList.toggle('relaxed',!$('compact-mode').checked);
$('right-panel').onchange=()=>document.body.classList.toggle('no-right',!$('right-panel').checked);
$('high-contrast').onchange=()=>document.body.classList.toggle('high-contrast',$('high-contrast').checked);
$('font-size').onchange=()=>document.documentElement.style.fontSize=$('font-size').value+'px';
document.addEventListener('keydown',event=>{if(/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||event.ctrlKey||event.metaKey)return;if(event.key==='[')$('toggle-left').click();if(event.key===']'){$('right-panel').checked=!$('right-panel').checked;$('right-panel').onchange();}});
function kcTitle(id){return $('target').querySelector('option[value="'+CSS.escape(id)+'"]')?.textContent||id;}
function renderPath(pathData){const nodes=document.createElement('div');nodes.className='path-nodes';for(const [index,node] of (pathData.nodes||[]).entries()){const card=document.createElement('article');card.className='path-node';card.dataset.decision=node.decision;card.append(text('h3',(index+1)+' '+kcTitle(node.kc_id)),text('p',labels[node.decision]||node.decision),text('p',node.reason),sourceDetails({evidence:node.evidence_refs,state_version:node.state_version}));nodes.append(card);}$('path').replaceChildren(text('p','路径提案 · 你可以采纳、修改或拒绝；不自动签署。'),nodes);$('path').className='';}
async function updateOverview(){if(!learner||!$('teaching-consent').checked)return;const [projects,workspace,reviews]=await Promise.all([api('/api/learning/projects/'+learner),api('/api/learning/plans/'+learner+'/workspace'),api('/api/learning/reviews/'+learner)]);const items=(projects.projects||projects.records||[]).filter(p=>!p.content.archived),box=$('sidebar-projects');box.replaceChildren();$('project-switch').replaceChildren();if(!items.length){box.append(text('p','暂无项目，请在计划中建立'));$('project-switch').append(text('option','当前学习项目'));}for(const project of items){const card=document.createElement('article');card.className='project-card';const btn=text('button',project.content.title);btn.onclick=()=>{show('plan');editProject(project);};const tasks=project.content.tasks||[],done=tasks.filter(t=>t.status==='done'||t.status==='completed').length;const progress=document.createElement('progress');progress.max=tasks.length||1;progress.value=done;card.append(btn,progress,text('small',done+'/'+tasks.length+' 项任务完成'));box.append(card);const option=text('option',project.content.title);option.value=project.record_id;$('project-switch').append(option);}$('project-switch').onchange=()=>{const p=items.find(p=>p.record_id===$('project-switch').value);if(p){show('plan');editProject(p);}};$('sidebar-goal').textContent=workspace.contract?.goal_statement?.text||'还没有学习目标';$('sidebar-plan').textContent=workspace.active?'当前计划已由你签署':'等待你审阅并签署计划';$('due-count').textContent=String(reviews.tasks.length);}
function clearOverview(){for(const id of ['mastery-chart','independent-chart','assistance-chart','kc-chart','sidebar-projects'])$(id).replaceChildren(text('p','授权撤回，内容已清除'));$('growth-source').textContent='';$('sidebar-goal').textContent='暂无授权目标';$('sidebar-plan').textContent='教学授权已撤回';$('due-count').textContent='—';$('project-switch').replaceChildren(text('option','当前学习项目'));}
async function loadGrowth(){const result=await api('/api/learning/growth/'+learner);WenjinCharts.line($('mastery-chart'),result.mastery.map(s=>({label:kcTitle(s.kc_id),points:s.points})),'当前有效证据重放的逐知识点掌握估计');WenjinCharts.line($('independent-chart'),[{label:'首次有效独立作答通过率',points:result.independent}],'首次有效独立作答累计通过率');WenjinCharts.line($('assistance-chart'),[{label:'累计使用提示/辅助比例',points:result.assistance}],'累计辅助作答比例');WenjinCharts.bars($('kc-chart'),result.current_mastery.map(m=>({label:kcTitle(m.kc_id),value:m.p_mastery})),'各知识点当前掌握估计');$('growth-source').textContent='来源：当前有效证据 '+result.effective_count+' 条 · 版本 '+result.projection_version+' · 修正后重述历史，不是当时记录的原始估计；'+(result.truncated?'图表仅显示最新200个节点。':'不包含写死成绩。');const select=$('appeal-evidence');select.replaceChildren(text('option','请选择要复核的作答'));select.firstChild.value='';for(const e of result.evidence_choices){const option=text('option',e.assessment_id+' · '+(labels[e.verdict_status]||e.verdict_status)+' · '+new Date(e.occurred_at).toLocaleString());option.value=e.evidence_id;select.append(option);}}
new MutationObserver(()=>{updateOverview().catch(e=>{if(e.name!=='AbortError')notice(e.message,true);});}).observe($('project-list'),{childList:true});
new MutationObserver(()=>{updateOverview().catch(e=>{if(e.name!=='AbortError')notice(e.message,true);});}).observe($('workspace-summary'),{childList:true});
function syncAssetSource(){const asset=selected();$('task-source').textContent=asset?'课程来源：'+asset.provenance+' · 校准状态：'+asset.calibration_status:'暂无课程资产';}
const sourceObserver=new MutationObserver(syncAssetSource);sourceObserver.observe($('assessment'),{childList:true});$('assessment').addEventListener('change',syncAssetSource);$('target').addEventListener('change',syncAssetSource);
$('collaboration-results').classList.add('roundtable-grid');
api('/api/learning/config').then(config=>{$('catalog-label').textContent='课程版本 '+config.catalog_version+' · 本地研究 MVP';}).catch(()=>{});
