'use strict';
const element=id=>document.getElementById(id),surface=document.body.dataset.surface;
let learner='',assets=[],rubrics=[],rubricInputs=new Map(),correctionRequest=null,qualitativeRequest=null;
let privacyEpoch=0;
const pending=new Set();
const privacyChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('wenjin-local-privacy'):null;
function clearPrivate(){privacyEpoch++;for(const controller of pending)controller.abort();correctionRequest=null;qualitativeRequest=null;for(const id of ['dashboard-result','artifact-result','correction-result','recovery-result','recovery-detail','import-result'])element(id)?.replaceChildren();for(const id of ['staff-token','correction-evidence','correction-reason','import-path','import-source'])if(element(id))element(id).value='';element('status').textContent='授权或登录状态已变化，请重新取得授权后查看。';}
privacyChannel?.addEventListener('message',event=>{if(['withdraw','sharing','logout'].includes(event.data?.kind))clearPrivate();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)clearPrivate();});
window.addEventListener('pagehide',clearPrivate);
function textNode(tag,value){const node=document.createElement(tag);node.textContent=String(value);return node;}
function detail(value){const node=document.createElement('details');node.append(textNode('summary','技术来源详情'),textNode('pre',JSON.stringify(value,null,2)));return node;}
async function request(url,body,headers={}){const epoch=privacyEpoch,controller=new AbortController();pending.add(controller);try{const response=await fetch(url,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});if(response.status===401){clearPrivate();location.assign('/login');throw Error('请先登录');}const result=await response.json();if(epoch!==privacyEpoch)throw new DOMException('Private view cleared','AbortError');if(!response.ok)throw Error(typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));return result;}finally{pending.delete(controller);}}
function bind(id,action){if(!element(id))return;element(id).onclick=async()=>{const button=element(id);if(button.disabled)return;button.disabled=true;button.setAttribute('aria-busy','true');element('status').textContent='处理中…';try{await action();element('status').classList.remove('error');element('status').textContent='操作完成';}catch(error){element('status').textContent=error.message;element('status').classList.add('error');}finally{button.disabled=false;button.removeAttribute('aria-busy');}};}
async function credential(action){const input=element('staff-token'),token=input.value;input.value='';if(!token)throw Error('请输入本次操作凭据');try{return await action(surface==='parent'?{'x-parent-token':token}:{'x-teacher-token':token});}finally{input.value='';}}
bind('load-dashboard',async()=>{element('dashboard-result').replaceChildren();await credential(async headers=>{const result=await request('/api/learning/dashboard/'+encodeURIComponent(learner)+'?audience='+surface,undefined,headers);const box=element('dashboard-result');box.append(textNode('h3',surface==='parent'?'家长看板':'教师看板'),textNode('p','证据 '+result.evidence_count+' 条 · 到期复习 '+result.review_due_count+' 项 · 项目 '+result.project_count+' 个'));for(const state of result.mastery_summary)box.append(textNode('p',state.kc_id+' · 掌握估计 '+Math.round(state.p_mastery*100)+'%'));for(const title of result.active_project_titles||[])box.append(textNode('p','学习项目 · '+title));if(surface==='teacher'){box.append(detail({evidence:result.evidence_refs,appeals:result.appeals,projects:result.projects}));}box.append(textNode('p','描述性摘要，不是教学效果、能力排名或医学诊断。'));});});
function clearReview(){correctionRequest=null;qualitativeRequest=null;element('artifact-result')?.replaceChildren();element('correction-result')?.replaceChildren();}
for(const id of ['correction-evidence','correction-status','correction-score','correction-confidence','correction-reason','assessor-version'])element(id)?.addEventListener('input',clearReview);
function rubric(){return rubrics.find(r=>r.ref.asset_id+'@'+r.ref.version===element('qualitative-rubric').value);}
function renderRubric(){qualitativeRequest=null;rubricInputs.clear();const box=element('rubric-dimensions');box.replaceChildren();for(const dimension of rubric()?.dimensions||[]){const label=textNode('label',dimension.description+' · '+dimension.dimension_id),input=document.createElement('input');input.type='number';input.min='0';input.max='1';input.step='.05';input.value='0';input.addEventListener('input',()=>qualitativeRequest=null);label.append(input);box.append(label);rubricInputs.set(dimension.dimension_id,input);}}
element('qualitative-rubric')?.addEventListener('change',renderRubric);
function recordId(){const id=element('correction-evidence').value.trim();if(!id)throw Error('请输入作答记录编号');return id;}
function numberValue(id){const v=Number(element(id).value);if(!Number.isFinite(v)||v<0||v>1)throw Error('分数和置信度必须为 0–1');return v;}
function reason(){const v=element('correction-reason').value.trim();if(!v)throw Error('请填写复核理由');return v;}
function showCorrection(result){element('correction-result').replaceChildren(textNode('p','修正已追加；待执行恢复任务，不自动签署。'),detail(result));element('correction-evidence').value=result.evidence_id;}
bind('teacher-correct',async()=>credential(async headers=>{if(!correctionRequest)correctionRequest={evidence_id:recordId(),correction_id:crypto.randomUUID(),status:element('correction-status').value,score:numberValue('correction-score'),confidence:numberValue('correction-confidence'),reason:reason(),rubric:{correctness:numberValue('correction-score')}};const result=await request('/api/learning/teacher/'+learner+'/corrections',correctionRequest,headers);correctionRequest=null;showCorrection(result);}));
bind('read-artifact',async()=>{element('artifact-result').replaceChildren();await credential(async headers=>{const result=await request('/api/learning/qualitative/'+learner+'/artifacts/'+encodeURIComponent(recordId()),undefined,headers);element('artifact-result').append(textNode('h3','授权作品'),textNode('p',result.content),detail({assessment_ref:result.assessment_ref,content_sha256:result.content_sha256}));const asset=assets.find(a=>a.ref.asset_id+'@'+a.ref.version===result.assessment_ref);if(asset){element('qualitative-rubric').value=asset.rubric_ref.asset_id+'@'+asset.rubric_ref.version;renderRubric();}});});
bind('qualitative-review',async()=>credential(async headers=>{const rule=rubric();if(!rule)throw Error('请选择评分规则');if(!qualitativeRequest)qualitativeRequest={evidence_id:recordId(),rubric_id:rule.ref.asset_id,rubric_version:rule.ref.version,dimension_scores:Object.fromEntries([...rubricInputs].map(([id,input])=>[id,Number(input.value)])),confidence:numberValue('correction-confidence'),reason:reason(),assessor_version:element('assessor-version').value.trim(),correction_id:crypto.randomUUID()};const result=await request('/api/learning/qualitative/'+learner+'/reviews',qualitativeRequest,headers);qualitativeRequest=null;showCorrection(result);}));
async function recoveryQueue(reconcile=false){const result=await request('/api/learning/recovery/'+learner+(reconcile?'/reconcile':''),reconcile?{}:undefined);const box=element('recovery-result');box.replaceChildren();element('recovery-detail').replaceChildren();if(!result.jobs.length)box.append(textNode('p','暂无待处理恢复任务'));for(const job of result.jobs){const row=document.createElement('div');row.className='band';row.append(textNode('p',job.status+' · '+job.correction_id+' · 已尝试 '+job.attempts+' 次'));const button=textNode('button','执行状态重建');button.onclick=async()=>{button.disabled=true;try{const updated=await request('/api/learning/recovery/'+learner+'/'+encodeURIComponent(job.job_id)+'/run',{});await recoveryQueue(false);element('recovery-detail').replaceChildren(textNode('p',updated.status==='completed'?'已完成重建；新提案等待学生审阅':'恢复状态：'+updated.status),detail(updated));}catch(error){element('status').textContent=error.message;}finally{button.disabled=false;}};row.append(button);box.append(row);}}
bind('refresh-recovery',()=>recoveryQueue());bind('reconcile-recovery',()=>recoveryQueue(true));
bind('import-knowledge',async()=>{const relative_path=element('import-path').value.trim(),source_id=element('import-source').value.trim();if(!relative_path||!source_id)throw Error('请填写受限目录内文件与来源编号');const result=await request('/api/knowledge/import',{relative_path,source_id,kc_refs:[element('import-kc').value],enable_ocr:element('import-ocr').checked});element('import-result').replaceChildren(textNode('p','本地来源已导入；仍是引用候选，不能替代课程审批'),detail(result));});
(async()=>{try{const config=await request('/api/learning/config');learner=config.learner_id;if(surface!=='parent'){const data=await request('/api/learning/assets');assets=data.assessments;if(surface==='teacher'){rubrics=data.rubrics.filter(r=>['teacher','reviewed_llm'].includes(r.assessor_policy));for(const r of rubrics){const option=textNode('option',r.ref.asset_id+' · '+r.ref.version);option.value=r.ref.asset_id+'@'+r.ref.version;element('qualitative-rubric').append(option);}renderRubric();}else for(const kc of data.knowledge){const option=textNode('option',kc.title);option.value=kc.ref.asset_id;element('import-kc').append(option);}}}catch(error){element('status').textContent=error.message;}})();
