const $=id=>document.getElementById(id);let learner='',assets=[],sessionId=null,path=null,planVersion=null,review=null,submission=null,sessionSubmission=null;
let savedPlans=[],goalSupported=true,planRejectLocked=false;
let requestedCoursePending=false;
let reviewListRequest=0;
let taskDelivery=null,deliveryReady=null,taskEpoch=0;
let projectEdit=null,projectTasks=[],projectCreateId=null;
let appealSubmission=null;
const labels={correct:'正确',passed:'验证通过',failed:'尚未通过',partial:'部分通过',unverifiable:'无法验证',mastered:'已掌握',not_mastered:'尚未掌握',insufficient_evidence:'证据不足',uncertain:'判断不确定',DIAGNOSE:'初诊',REVIEW:'复习',REMEDIATE:'补练',ADVANCE:'进阶',explanation:'讲解练习',diagnostic:'初诊',practice:'练习',pretest:'前测',posttest:'后测',transfer:'迁移测',delayed:'延迟复习'};
function notice(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error)}
let privacyEpoch=0,signingOut=false;const pendingRequests=new Set();
const privacyChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('wenjin-local-privacy'):null;
function notifyPrivacyChange(kind){privacyChannel?.postMessage({kind});}
privacyChannel?.addEventListener('message',event=>{if(event.data?.kind==='withdraw'||event.data?.kind==='logout'){clearLearningView();loadConsent().catch(()=>{});}});
async function api(url,body,method,headers={}){const epoch=privacyEpoch,controller=new AbortController();pendingRequests.add(controller);try{const response=await fetch(url,{method:method||(body?'POST':'GET'),headers:{'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined,signal:controller.signal});if(response.status===401){if(!signingOut)location.assign('/login');throw new DOMException('Authentication required','AbortError')}const data=await response.json();if(epoch!==privacyEpoch)throw new DOMException('Learning view cleared','AbortError');if(!response.ok){const detail=typeof data.detail==='string'?data.detail:JSON.stringify(data.detail);if(response.status===403&&/consent|教学|授权|teaching/i.test(detail)){show('settings');throw Error('请先在“授权”页确认教学用途，再继续学习或计划操作')}const error=Error(detail);error.status=response.status;throw error}return data}finally{pendingRequests.delete(controller)}}
$('logout').onclick=async()=>{signingOut=true;try{await fetch('/api/auth/logout',{method:'POST'})}finally{notifyPrivacyChange('logout');clearLearningView();location.assign('/login')}};
function run(fn){return async(event)=>{const button=event?.currentTarget?.tagName==='BUTTON'?event.currentTarget:null;if(button?.dataset.busy)return;if(button){button.dataset.busy='1';button.disabled=true;button.setAttribute('aria-busy','true')}try{await fn()}catch(e){if(e.name!=='AbortError')notice(e.message,true)}finally{if(button){delete button.dataset.busy;button.removeAttribute('aria-busy');const planAction=['sign-plan','modify-plan'].includes(button.id);button.disabled=button.id==='reject-plan'?planRejectLocked:planAction?planLocked:button.id==='draft-plan'?!path:false}}}}
function text(tag,value){const el=document.createElement(tag);el.textContent=value;return el}
let planLocked=false;
function renderPlan(status,diff={}){const states={draft:'草案，待学习者签署',proposed:'建议，待采纳',confirmed:'已签署并生效',rejected:'已拒绝',superseded:'已被新版本替代'};const box=$('plan-detail');box.replaceChildren(text('h3','计划状态：'+(states[status]||status)));const pathChange=diff.path;if(pathChange){const before=new Map((pathChange.before?.nodes||[]).map(n=>[n.kc_id,n]));const after=pathChange.after?.nodes||[];const table=document.createElement('table');const header=document.createElement('tr');['知识点','调整前','调整后','依据'].forEach(v=>header.append(text('th',v)));table.append(header);after.forEach(n=>{const tr=document.createElement('tr');[n.kc_id,before.has(n.kc_id)?labels[before.get(n.kc_id).decision]||before.get(n.kc_id).decision:'未安排',labels[n.decision]||n.decision,n.reason].forEach(v=>tr.append(text('td',v)));table.append(tr)});const wrap=document.createElement('div');wrap.className='table-wrap';wrap.append(table);box.append(wrap)}for(const [key,label] of [['cadence','学习节奏'],['learner_notes','调整说明']])if(diff[key])box.append(text('p',label+'：'+(diff[key].before||'未设置')+' → '+(diff[key].after||'未设置')));if(diff.bank_scope)box.append(text('p','学习范围：'+(diff.bank_scope.after||[]).join('、')));if(Object.keys(diff).length){const detail=document.createElement('details');detail.append(text('summary','变更记录'),text('pre',JSON.stringify(diff,null,2)));box.append(detail)}}
function sourceDetails(refs){const detail=document.createElement('details');detail.append(text('summary','来源引用'),text('pre',JSON.stringify(refs,null,2)));return detail}
function show(view){if(document.body.dataset.view!==view){notice('');window.scrollTo(0,0);}document.body.dataset.view=view;for(const s of document.querySelectorAll('main>section'))s.hidden=s.id!==view;for(const b of document.querySelectorAll('nav button')){const selected=b.dataset.view===view;b.setAttribute('aria-selected',selected);b.tabIndex=selected?0:-1}}
const tabs=[...document.querySelectorAll('nav button')];
function activateTab(button){show(button.dataset.view);if(button.dataset.view==='reviews')run(loadReviews)();if(button.dataset.view==='evidence')run(loadEvidence)()}
tabs.forEach((button,index)=>{button.onclick=()=>activateTab(button);button.onkeydown=event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();activateTab(tabs[next]);tabs[next].focus()}});
function selected(){return assets.find(a=>a.ref.asset_id===$('assessment').value)}
function syncContext(){const kc=$('target').selectedOptions[0];$('aside-kc').textContent=kc?.textContent||'暂无任务';$('aside-task').textContent=$('task-stem').textContent;$('aside-verdict').textContent=$('verdict').textContent||'暂无验证结果';$('aside-consent').textContent=$('consent-status').textContent}
const contextObserver=new MutationObserver(syncContext);for(const id of ['task-stem','verdict','consent-status','target'])contextObserver.observe($(id),{childList:true,subtree:true,characterData:true});$('target').addEventListener('change',syncContext);
function chooseTask(){const a=selected(),epoch=++taskEpoch;review=null;submission=null;taskDelivery=null;deliveryReady=null;
  // A task change starts a new conversation context. Keeping the old bubbles here
  // makes the visible question disagree with the latest assistant reply.
  $('chat').replaceChildren(text('p',a?'已切换到新题目，可以开始作答。':'暂无会话'));
  $('assisted').checked=false; sessionId=null; sessionSubmission=null;
  $('task-stem').textContent=a?'加载任务中…':'暂无任务';$('answer').value='';$('message').value='';$('message').maxLength=a?.kind==='explanation'?8000:1000;$('study-task-title').textContent=$('target').selectedOptions[0]?.textContent||'陪津津一起探究';$('study-task-meta').textContent=a?`${labels[a.kind]||a.kind} · 先写答案，再决定是否需要提示`:'选一道题，先说说你的想法，再决定是否需要提示。';$('submit').textContent=a?.kind==='explanation'?'提交作品待评审':'验证这道题';$('self-report').value='answered';$('self-report').disabled=a?.kind==='explanation';$('verdict').textContent='';if(a&&$('teaching-consent').checked){deliveryReady=api('/api/learning/assessment/'+learner+'/issue',{assessment_id:a.ref.asset_id,assessment_version:a.ref.version,issuance_id:crypto.randomUUID()}).then(result=>{if(epoch!==taskEpoch)return;taskDelivery=result;$('task-stem').textContent=result.assessment.stem;return result});deliveryReady.catch(e=>{if(epoch===taskEpoch&&e.name!=='AbortError')notice(e.message,true)})}else if(a?.stem)$('task-stem').textContent=a.stem}
function changeTarget(){const items=assets.filter(a=>a.kc_refs.some(k=>k.asset_id===$('target').value)&&a.kind!=='delayed');$('assessment').replaceChildren(...items.map(a=>{const number=items.filter(item=>item.kind===a.kind).indexOf(a)+1;const opt=text('option',`${labels[a.kind]||a.kind} · 第 ${number} 题`);opt.title=a.ref.asset_id;opt.value=a.ref.asset_id;return opt}));chooseTask()}
$('target').onchange=changeTarget;$('assessment').onchange=chooseTask;$('answer').oninput=()=>submission=null;$('assisted').onchange=()=>submission=null;$('self-report').onchange=()=>submission=null;$('session-answer').oninput=()=>sessionSubmission=null;
$('message').addEventListener('input',()=>{$('answer').value=$('message').value;$('session-answer').value=$('message').value;submission=null;sessionSubmission=null});
async function requestAssessmentHint(){const epoch=taskEpoch;await deliveryReady;const a=selected();if(epoch!==taskEpoch||!taskDelivery||!a)throw Error('请先获取学习任务');if(review||['pretest','posttest','transfer','delayed'].includes(a.kind))throw Error('测量与复习任务不提供提示；可以选择练习任务');if(taskDelivery.consumed){taskDelivery=await api('/api/learning/assessment/'+learner+'/issue',{assessment_id:a.ref.asset_id,assessment_version:a.ref.version,issuance_id:crypto.randomUUID()});if(epoch!==taskEpoch)return}const result=await api('/api/learning/assessment/'+learner+'/hint',{assessment_id:a.ref.asset_id,assessment_version:a.ref.version,delivery_ref:taskDelivery.delivery_ref,level:1});$('assisted').checked=true;submission=null;addChat('津津 · 当前题目提示',result.hint);notice('当前题目提示已记录，本次作答将标记为使用提示')}
$('help').onclick=run(requestAssessmentHint);
async function loadConsent(){const data=await api('/api/learning/consent/'+learner);const yes=data.consent?.scopes.includes('teaching');$('teaching-consent').checked=!!yes;$('consent-status').textContent=yes?'教学用途已授权':'教学用途未授权';return yes}
$('authorize').onclick=run(async()=>{if(!$('teaching-consent').checked)throw Error('请确认教学用途授权');await api('/api/learning/consent/'+learner,{scopes:['teaching'],version:'learner:'+crypto.randomUUID(),source:'local-learner-explicit'});await loadConsent();changeTarget();await restorePlanWorkspace();await restoreWorkspaceExtras();notice('授权已保存');show('study')});
function clearLearningView(){
  privacyEpoch++;for(const request of pendingRequests)request.abort();
  taskEpoch++;taskDelivery=null;deliveryReady=null;
  sessionId=null;path=null;planVersion=null;review=null;submission=null;sessionSubmission=null;savedPlans=[];appealSubmission=null;
  projectEdit=null;projectTasks=[];projectCreateId=null;planLocked=true;
  for(const id of ['answer','session-answer','session-recovery-id','message','goal','cadence','plan-notes','project-title','project-description','project-task-title','project-evidence-refs','project-session-refs','project-source-refs','appeal-evidence','appeal-reason','development-split','knowledge-query','collaboration-work','teach-lesson'])if($(id))$(id).value='';
  $('assisted').checked=false;$('self-report').value='answered';$('share-audience').value='none';
  $('verdict').textContent='';$('chat').replaceChildren(text('p','暂无会话'));$('path').replaceChildren(text('p','暂无路径建议'));$('plan-detail').replaceChildren();$('workspace-summary').textContent='';
  $('saved-plan').replaceChildren(text('option','暂无已保存计划'));$('project-list').replaceChildren(text('p','暂无项目'));$('project-task-editor').replaceChildren();$('sharing-status').textContent='尚未保存共享对象';
  reviewListRequest++;
  $('review-scope').textContent='仅显示当前已到期的复习任务。';
  $('state-list').replaceChildren();$('evidence-list').replaceChildren();$('review-list').replaceChildren(text('p','暂无复习任务'));$('metric-result').replaceChildren(text('p','暂无可比较数据'));$('memory-result').replaceChildren(text('p','暂无记忆摘要'));$('development-result').replaceChildren(text('p','暂无发展指标'));$('appeal-result').replaceChildren();$('assessment').replaceChildren();$('task-stem').textContent='选择学习任务';$('metric-kind').value='posttest';
  for(const id of ['knowledge-results','strategy-results','collaboration-results','teach-results','collaboration-evidence'])if($(id))$(id).replaceChildren();
  $('collaboration-status').textContent='';$('collaboration-status').classList.remove('error');
  for(const id of ['draft-plan','sign-plan','reject-plan','modify-plan','save-project','save-sharing'])if($(id))$(id).disabled=true;clearOverview();show('settings')
}
$('withdraw').onclick=run(async()=>{await api('/api/learning/consent/'+learner,null,'DELETE');notifyPrivacyChange('withdraw');clearLearningView();await loadConsent();notice('教学授权已撤回，当前学习内容已清除')});
$('diagnose').onclick=run(async()=>{const result=await api('/api/learning/diagnosis/'+learner+'/next',{target_kc_id:$('target').value});if(result.assessment){const a=result.assessment;if(![...$('assessment').options].some(o=>o.value===a.ref.asset_id)){const o=text('option',a.ref.asset_id+' · 初诊');o.value=a.ref.asset_id;$('assessment').append(o)}$('assessment').value=a.ref.asset_id;chooseTask();notice('初诊任务已就绪')}else notice({complete:'初诊完成',needs_learning:'先修知识需要补练',budget_exhausted:'诊断预算已用完，保留未知状态',missing_assets:'诊断题目不足，保留未知状态'}[result.decision.status]||result.decision.reason)});
// Formal assessment submissions carry the active project; temporary sessions
// are routed through their isolated context API below and never reach this path.
$('submit').onclick=run(async()=>{const a=selected(),epoch=taskEpoch;$('answer').value=$('message').value;if(!a||(!$('answer').value.trim()&&$('self-report').value==='answered'))throw Error('请填写作答');const qualitative=a.kind==='explanation';if(!qualitative){await deliveryReady;if(epoch!==taskEpoch||!taskDelivery)throw Error('请重新选择任务以获取发题凭据');if(!submission&&taskDelivery.consumed){taskDelivery=await api('/api/learning/assessment/'+learner+'/issue',{assessment_id:a.ref.asset_id,assessment_version:a.ref.version,issuance_id:crypto.randomUUID()});if(epoch!==taskEpoch)return}}if(!submission){const assist=$('assisted').checked;submission={assessment_id:a.ref.asset_id,assessment_version:a.ref.version,attempt_id:crypto.randomUUID(),project_id:activeProjectId,hint_level:assist?1:0,assistance_mode:assist?'hint':'none',answer_exposed:false,...(qualitative?{content:$('answer').value}:{answer:$('answer').value,occurred_at:new Date().toISOString(),self_report:$('self-report').value,delivery_ref:taskDelivery.delivery_ref})};if(review)submission.task_id=review.task_id}const result=await api(qualitative?'/api/learning/qualitative/'+learner+'/artifacts':'/api/learning/'+(review?'reviews':'assessment')+'/'+learner+'/submit',submission);if(!qualitative)taskDelivery.consumed=true;const verdict=qualitative?'作品已保存，待匹配 Rubric 的教师评审':labels[result.verdict_status]||result.verdict_status;$('verdict').textContent=verdict;addChat('我的作答',$('answer').value||'本题选择了“'+$('self-report').selectedOptions[0].textContent+'”');addChat('验证结果',verdict);notice(qualitative?'作品与待验证证据已保存，不计入掌握更新':'作答与学习证据已保存');$('message').value='';$('answer').value='';$('session-answer').value='';await updateOverview();if(review)await loadReviews()});
$('appeal-evidence').oninput=$('appeal-reason').oninput=()=>appealSubmission=null;
$('submit-appeal').onclick=run(async()=>{if(!$('appeal-evidence').value.trim()||!$('appeal-reason').value.trim())throw Error('请填写证据编号和申诉理由');if(!appealSubmission)appealSubmission={evidence_id:$('appeal-evidence').value.trim(),reason:$('appeal-reason').value.trim(),appeal_id:'appeal:'+crypto.randomUUID()};const result=await api('/api/learning/appeals/'+learner,appealSubmission);$('appeal-result').replaceChildren(text('p','申诉已提交 · '+result.appeal_id));notice('申诉已保存，等待人工复核')});
async function checkGoalCoverage(){const goal=$('goal').value.trim();if(goal.length<2){$('goal-coverage').textContent='请先输入至少两个字的学习目标。';return null}const data=await api('/api/goals/coverage?goal_text='+encodeURIComponent(goal)+'&learner_id='+encodeURIComponent(learner));$('goal-coverage').textContent=data.supported?'已找到课程：'+data.target_titles.join('、')+'。可以建立目标并查看路径。':'当前没有可直接学习的课程。继续后会登记课程需求，等待资料与审核。';$('goal-coverage').dataset.supported=String(data.supported);return data}
async function loadCourseRequests(){const result=await api('/api/course-requests?learner_id='+encodeURIComponent(learner));const box=$('course-requests');box.replaceChildren();if(!result.requests.length){box.textContent='尚无课程需求';return}for(const item of result.requests){const card=document.createElement('article');card.className='course-request';const label=item.status==='needs_review'?'找到本地候选资料 · 待课程审核':'尚缺可信资料 · 待准备课程';card.append(text('strong',item.goal_text),text('span',label),text('p','本地资料候选 '+item.analysis.local_source_candidates.length+' 份；后续需制作知识点、题目与评测并完成审核。'));box.append(card)}}
$('goal').addEventListener('change',()=>{checkGoalCoverage().catch(e=>{if(e.name!=='AbortError')$('goal-coverage').textContent=e.message})});
$('save-goal').onclick=run(async()=>{const coverage=await checkGoalCoverage();if(!coverage)throw Error('请填写学习目标');if(!coverage.supported){const request=await api('/api/course-requests',{goal_text:$('goal').value,learner_id:learner});await loadCourseRequests();requestedCoursePending=true;taskEpoch++;taskDelivery=null;deliveryReady=null;$('assessment').replaceChildren();$('task-stem').textContent='课程正在准备中，尚无可练习题目';$('study-task-title').textContent=$('goal').value;$('study-task-meta').textContent='课程需求已登记；准备并审核后才能开始学习。';$('chat').replaceChildren();$('study-open-plan').hidden=false;notice('课程需求已登记：'+(request.status==='needs_review'?'已有本地候选资料，仍需审核':'需要补充可信资料并完成课程审核'));return}await api('/api/contracts',{goal_text:$('goal').value,learner_id:learner});requestedCoursePending=false;$('study-open-plan').hidden=true;await restorePlanWorkspace();notice('学习目标已建立')});
$('get-path').onclick=run(async()=>{path=null;$('draft-plan').disabled=true;$('path').replaceChildren(text('p','正在核对目标与当前课程…'));try{path=await api('/api/path/recommend?learner_id='+encodeURIComponent(learner))}catch(error){$('path').replaceChildren(text('p',error.message));throw error}renderPath(path);$('draft-plan').disabled=false;notice('路径建议已更新')});
$('draft-plan').onclick=run(async()=>{const saved=savedPlans.find(plan=>plan.version_id===planVersion&&plan.status==='proposed');if(saved)await api('/api/learning/plans/'+learner+'/'+encodeURIComponent(saved.version_id)+'/accept',{});else await api('/api/path/accept',{learner_id:learner,path});await restorePlanWorkspace();notice('已生成计划草案，请审阅变更')});
$('modify-plan').onclick=run(async()=>{const current=await api('/api/plans/'+encodeURIComponent(planVersion)+'?learner_id='+encodeURIComponent(learner));const reason=$('plan-notes').value.trim();if(!reason)throw Error('请说明调整原因');await api('/api/plans/'+encodeURIComponent(planVersion)+'/modify',{learner_id:learner,content:{...current.content,cadence:$('cadence').value,learner_notes:reason},reason});await restorePlanWorkspace();notice('草案已修改，请重新审阅并签署')});
$('sign-plan').onclick=run(async()=>{await api('/api/plans/'+encodeURIComponent(planVersion)+'/sign',{learner_id:learner});await restorePlanWorkspace();notice('计划已签署')});
$('reject-plan').onclick=run(async()=>{await api('/api/plans/'+encodeURIComponent(planVersion)+'/reject',{learner_id:learner,reason:'学习者拒绝'});await restorePlanWorkspace();notice('拒绝已记录')});
function addChat(who,message){const own=who==='我'||who==='我的作答';const bubble=document.createElement('div');bubble.className='study-bubble '+(own?'user-bubble':'companion-bubble');const avatar=text('div',own?'我':'津');avatar.className='study-avatar';avatar.setAttribute('aria-hidden','true');const body=document.createElement('div');body.className='study-bubble-body';const name=text('div',who+' · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}));name.className='study-sender';const content=text('div',message);content.className='study-message';body.append(name,content);bubble.append(avatar,body);$('chat').append(bubble);$('chat').parentElement.scrollTop=$('chat').parentElement.scrollHeight}
function restorePlanSelection(){const plan=savedPlans.find(item=>item.version_id===$('saved-plan').value);planVersion=plan?.version_id||null;planRejectLocked=!plan||plan.status!=='draft';planLocked=planRejectLocked||!goalSupported;$('sign-plan').disabled=planLocked;$('modify-plan').disabled=planLocked;$('reject-plan').disabled=planRejectLocked;path=goalSupported?plan?.content.path||null:null;$('draft-plan').disabled=!path;if(!goalSupported)$('path').replaceChildren(text('p','当前目标不在已导入课程中，不能使用之前生成的方程路径或签署旧草案。请改为现有课程目标，或先导入并审核新课程。'));else if(path)renderPath(path);else $('path').replaceChildren(text('p','暂无路径建议'));if(!plan){$('plan-detail').replaceChildren();return}renderPlan(plan.status,plan.diff||{});if(!goalSupported)$('plan-detail').prepend(text('p','此草案对应的课程范围与当前目标不匹配，已禁止签署。'));$('cadence').value=plan.content.cadence||'';$('plan-notes').value=plan.content.learner_notes||'';if(!Object.keys(plan.diff||{}).length) $('plan-detail').append(text('p','计划内容：'+(plan.content.cadence||plan.content.learner_notes||'沿用已保存学习安排')))}
async function restorePlanWorkspace(){const workspace=await api('/api/learning/plans/'+learner+'/workspace');goalSupported=workspace.goal_supported!==false;savedPlans=[...workspace.drafts,...workspace.proposals,...(workspace.active?[workspace.active]:[])];$('goal').value=workspace.contract?.goal_statement?.text||'';$('workspace-summary').textContent=workspace.contract?(goalSupported?'已保存目标 · 有效计划 '+(workspace.active?'1':'0')+' · 待签署草案 '+workspace.drafts.length+' · 待采纳建议 '+workspace.proposals.length:'已保存目标，但当前课程不支持；旧方程草案不可签署'):'暂无已保存目标';$('saved-plan').replaceChildren();if(!savedPlans.length){const option=text('option','暂无已保存计划');option.value='';$('saved-plan').append(option)}else for(const plan of savedPlans){const option=text('option',({draft:'待签署草案',confirmed:'当前有效计划',proposed:'待采纳建议'}[plan.status]||plan.status)+' · '+plan.version_id.slice(0,12));option.value=plan.version_id;$('saved-plan').append(option)}restorePlanSelection();if(!goalSupported){$('assessment').replaceChildren();$('task-stem').textContent='当前目标暂无可用课程任务';$('study-task-meta').textContent='请在计划页改为已导入课程目标，或先准备并审核新课程。';$('chat').replaceChildren(text('p','当前目标还没有可用题目。'));}else{changeTarget();}await loadCourseRequests()}
$('saved-plan').onchange=restorePlanSelection;$('restore-plans').onclick=run(restorePlanWorkspace);
function editProject(project){projectEdit=project;projectCreateId=null;projectTasks=(project?.content.tasks||[]).map(task=>({...task}));$('project-title').value=project?.content.title||'';$('project-description').value=project?.content.description||'';for(const [id,key] of [['project-evidence-refs','evidence_refs'],['project-session-refs','session_refs'],['project-source-refs','source_refs']])$(id).value=(project?.content[key]||[]).join('\n');renderProjectTasks();$('project-title').focus()}
async function loadProjects(){const result=await api('/api/learning/projects/'+learner);const box=$('project-list');box.replaceChildren();if(!result.projects.length)box.append(text('p','暂无项目'));for(const project of result.projects){const row=document.createElement('div');row.className='band';row.append(text('h3',project.content.title+(project.content.archived?' · 已归档':'')),text('p',project.content.description),text('p','版本 '+project.revision+' · '+project.content.tasks.length+' 项任务'));for(const task of project.content.tasks)row.append(text('p',task.title+' · '+({todo:'待办',doing:'进行中',done:'完成'}[task.status])));const edit=text('button','修改项目');edit.onclick=()=>editProject(project);const archive=text('button',project.content.archived?'恢复项目':'归档项目');archive.onclick=run(async()=>{await api('/api/learning/projects/'+learner,{content:{...project.content,archived:!project.content.archived},record_id:project.record_id,expected_revision:project.revision});await loadProjects()});row.append(edit,archive,sourceDetails({evidence:project.content.evidence_refs,sessions:project.content.session_refs,sources:project.content.source_refs}));box.append(row)}}
function renderProjectTasks(){const box=$('project-task-editor');box.replaceChildren();for(const task of projectTasks){const row=document.createElement('div');row.className='row';const title=document.createElement('input');title.value=task.title;title.setAttribute('aria-label','任务名称');title.onchange=()=>task.title=title.value;const status=document.createElement('select');status.setAttribute('aria-label','任务状态');for(const [value,label] of [['todo','待办'],['doing','进行中'],['done','完成']]){const option=text('option',label);option.value=value;status.append(option)}status.value=task.status;status.onchange=()=>task.status=status.value;const remove=text('button','移除');remove.onclick=()=>{projectTasks=projectTasks.filter(item=>item.task_id!==task.task_id);renderProjectTasks()};row.append(title,status,remove);box.append(row)}}
$('add-project-task').onclick=()=>{const title=$('project-task-title').value.trim();if(!title)return notice('请填写任务名称',true);projectTasks.push({task_id:crypto.randomUUID(),title,status:'todo',assessment_ref:null});$('project-task-title').value='';renderProjectTasks()};
$('new-project').onclick=()=>editProject(null);
function projectRefs(id){return [...new Set($(id).value.split(/[\n,，]+/).map(value=>value.trim()).filter(Boolean))]}
$('save-project').onclick=run(async()=>{const title=$('project-title').value.trim();if(!title)throw Error('请填写项目名称');if(!projectEdit&&!projectCreateId)projectCreateId='project:'+crypto.randomUUID();await api('/api/learning/projects/'+learner,{record_id:projectEdit?.record_id||projectCreateId,expected_revision:projectEdit?.revision||0,content:{...(projectEdit?.content||{}),title,description:$('project-description').value.trim(),tasks:projectTasks,evidence_refs:projectRefs('project-evidence-refs'),session_refs:projectRefs('project-session-refs'),source_refs:projectRefs('project-source-refs'),archived:projectEdit?.content.archived||false}});editProject(null);await loadProjects();notice('项目版本已保存')});
async function sharingRecord(){try{return await api('/api/learning/sharing/'+learner)}catch(error){if(error.message==='No explicit audience sharing record')return null;throw error}}
$('save-sharing').onclick=run(async()=>{const current=await sharingRecord();const audience=$('share-audience').value;const result=await api('/api/learning/sharing/'+learner,{audiences:audience==='none'?[]:audience==='both'?['teacher','parent']:[audience],expected_revision:current?.revision||0});notifyPrivacyChange('sharing');$('sharing-status').textContent='共享版本 '+result.revision+' · '+(result.content.audiences.map(a=>a==='teacher'?'教师':'家长').join('、')||'未共享');notice('共享选择已保存')});
async function restoreWorkspaceExtras(){projectEdit=null;projectTasks=[];for(const id of ['save-project','save-sharing'])$(id).disabled=false;await loadProjects();const record=await sharingRecord();const audiences=record?.content.audiences||[];$('share-audience').value=audiences.length===2?'both':audiences[0]||'none';$('sharing-status').textContent=record?'共享版本 '+record.revision+' · '+(audiences.map(a=>a==='teacher'?'教师':'家长').join('、')||'未共享'):'尚未保存共享对象';await updateOverview()}
async function loadCollaborationEvidence(){const [evidence,providers]=await Promise.all([api('/api/learning/evidence/'+learner),api('/api/providers')]);const replaced=new Set(evidence.map(item=>item.supersedes).filter(Boolean));$('collaboration-evidence').replaceChildren();for(const item of evidence.filter(item=>!replaced.has(item.evidence_id))){const option=text('option',item.assessment_id+' · '+(labels[item.verdict_status]||item.verdict_status));option.value=item.evidence_id;option.title=item.evidence_id;$('collaboration-evidence').append(option)}$('collaboration-provider').replaceChildren();for(const provider of providers.providers){const option=text('option',provider.provider_id==='offline'?'离线固定模板':provider.provider_id+' · '+provider.model);option.value=provider.provider_id;$('collaboration-provider').append(option)}notice('有效证据与执行来源已刷新')}
$('refresh-collaboration-evidence').onclick=run(loadCollaborationEvidence);
function collaborationBody(){const evidence_ids=[...$('collaboration-evidence').selectedOptions].map(option=>option.value);if(!evidence_ids.length)throw Error('请选择至少一条当前有效证据');const max_tokens=Number($('collaboration-tokens').value);if(!Number.isInteger(max_tokens)||max_tokens<1||max_tokens>4000)throw Error('输出预算必须为 1–4000');const provider_id=$('collaboration-provider').value;return {evidence_ids,student_work:$('collaboration-work').value,learner_id:learner,provider_id,max_tokens,deadline_ms:provider_id==='configured'?30000:3000}}
function candidateActionText(action){return action.params?.text||action.params?.stem||action.params?.question||'暂无可显示的候选文本'}
function appendCandidateReport(box,result){const report=result.report;const part=document.createElement('div');part.className='band';part.append(text('h3',({prompter:'提示者',skeptic:'怀疑者',reviewer:'评审者',teach_virtual_student:'虚拟学生'}[report.role]||report.role)),text('p',(result.execution_mode==='deterministic_demo'?'离线固定模板':'配置模型输出')+' · 待验证候选 · '+report.exit_status));if(report.exit_status==='constraint_violation')part.append(text('p','这份候选未通过角色或教学规则检查，不能作为建议使用。'));if(report.reason)part.append(text('p','检查原因：'+report.reason));for(const observation of report.observations||[])part.append(text('p',observation));if(report.misconception)part.append(text('p',report.misconception));if(report.rationale)part.append(text('p',report.rationale));for(const action of report.actions||[])part.append(text('p',candidateActionText(action)));part.append(text('p','未直接写入学习状态或签署计划。'),sourceDetails({report_id:result.report_id,evidence:report.evidence_refs||report.provenance?.evidence_refs,artifacts:report.artifact_refs,kc:report.kc_refs,provenance:result.provenance,source_refs:result.source_refs,reviews:report.reviews,actions:report.actions}));box.append(part)}
async function collaborationRequest(url,body,pending,render,done){const status=$('collaboration-status');status.classList.remove('error');status.textContent=pending;try{const result=await api(url,body);render(result);status.textContent=done;notice(done)}catch(error){if(error.name==='AbortError')throw error;status.classList.add('error');status.textContent=error.status===429?'请求过于频繁，请稍后重试。':'请求失败：'+error.message;throw error}}
$('role-review').onclick=run(async()=>{const body=collaborationBody();await collaborationRequest('/api/roles/'+$('collaboration-role').value+'/review',body,'正在生成单角色建议，配置模型最多等待约 30 秒…',result=>{$('collaboration-results').replaceChildren();appendCandidateReport($('collaboration-results'),result)},'单角色候选建议已生成')});
$('roundtable-review').onclick=run(async()=>{const body={...collaborationBody(),roles:['prompter','skeptic','reviewer']};await collaborationRequest('/api/roundtable/review',body,'正在依次生成三角色候选，配置模型可能需要较长时间…',result=>{const box=$('collaboration-results');box.replaceChildren(text('p','三角色候选，未评估共识；需要后续验证。'));for(const report of result.reports)appendCandidateReport(box,report)},'圆桌候选建议已生成')});
$('teach-student').onclick=run(async()=>{const lesson=$('teach-lesson').value.trim();if(!lesson)throw Error('请填写自己的讲解');const result=await api('/api/teach-student/lesson',{...collaborationBody(),lesson});$('teach-results').replaceChildren();appendCandidateReport($('teach-results'),result);notice('虚拟学生候选误区已生成，等待你的检查')});
$('load-strategies').onclick=run(async()=>{const result=await api('/api/strategies?kc_id='+encodeURIComponent($('target').value));const box=$('strategy-results');box.replaceChildren();if(!result.cards.length)box.append(text('p','当前知识点暂无策略卡'));for(const card of result.cards){const part=document.createElement('div');part.className='band';part.append(text('h3',card.purpose),text('p','策略 '+card.strategy_id+'@'+card.version+' · 待人工审阅'));const steps=document.createElement('ol');card.steps.forEach(step=>steps.append(text('li',step)));part.append(steps,text('p','自查：'+card.checks.join('；')),sourceDetails({kc:card.kc_refs,provenance:card.provenance,calibrated:card.calibrated}));box.append(part)}notice('策略候选卡已加载')});
$('search-knowledge').onclick=run(async()=>{const query=$('knowledge-query').value.trim();if(!query)throw Error('请填写检索问题');const result=await api('/api/knowledge/search?q='+encodeURIComponent(query)+'&kc_id='+encodeURIComponent($('target').value)+'&mode='+$('knowledge-mode').value);const box=$('knowledge-results');box.replaceChildren(text('p','引用候选，未经教学验证；向量为词特征，不是神经语义模型。'));if(!result.results.length)box.append(text('p','暂无匹配且有效的来源'));for(const source of result.results){const part=document.createElement('div');part.className='band';part.append(text('h3',source.source_id),text('p',source.text));const link=text('a','查看原文');link.href=source.source_url;link.target='_blank';link.rel='noopener';part.append(link,sourceDetails({version:source.source_version,chunk:source.chunk_id,citation:source.citation,kc:source.kc_refs}));box.append(part)}notice('知识引用候选已检索')});
async function startSession(){if(typeof activeContextId!=='undefined'&&activeContextId){sessionId=null;sessionSubmission=null;notice('临时会话已就绪，不会写入正式学习证据');return}const result=await api('/api/sessions',{learner_id:learner,session_type:'explore',project_id:activeProjectId});sessionId=result.session_id;$('session-recovery-id').value=sessionId;sessionSubmission=null;const note=text('p','自由陪学探究 · 会话可能安排另一道题；上方课程题仍用“验证这道题”核对');note.className='study-system-note';$('chat').append(note);addChat('津津 · 自由探究',result.reply);notice('自由陪学会话已开始')}
$('new-session').onclick=run(startSession);
$('restore-session').onclick=run(async()=>{const sid=$('session-recovery-id').value.trim();if(!sid)throw Error('请填写已保存的 Session ID');const result=await api('/api/sessions/'+encodeURIComponent(sid));sessionId=result.session_id;sessionSubmission=null;$('session-recovery-id').value=sessionId;const restored=text('p','已恢复自由陪学会话 · '+result.turn_count+' 轮；上方课程题仍用“验证这道题”核对');restored.className='study-system-note';$('chat').replaceChildren(restored);if(result.ui.current_item)addChat('自由探究题目',result.ui.current_item);$('session-recovery-id').closest('.study-options').open=false;notice('自由陪学会话已恢复，可以继续作答或求助')});
$('session-submit').onclick=run(async()=>{if(typeof activeContextId!=='undefined'&&activeContextId){const message=$('message').value.trim();if(!message)throw Error('请填写临时会话内容');const result=await api('/api/learning/contexts/'+learner+'/'+activeContextId+'/messages',{message_id:crypto.randomUUID(),text:message});addChat('我',message);addChat('临时伙伴',result.reply);$('message').value='';notice('临时讨论已保存，不计入正式画像');return}if(!sessionId)await startSession();$('session-answer').value=$('message').value;if(!$('session-answer').value.trim())throw Error('请填写会话作答');if(!sessionSubmission)sessionSubmission={answer:$('session-answer').value,attempt_id:crypto.randomUUID()};const result=await api('/api/sessions/'+sessionId+'/messages',sessionSubmission);addChat('我的作答',sessionSubmission.answer);addChat('津津',result.reply);$('message').value='';notice('会话作答已保存')});
async function send(message){if(!message.trim())throw Error('请先写下想法或问题');if(typeof activeContextId!=='undefined'&&activeContextId){const result=await api('/api/learning/contexts/'+learner+'/'+activeContextId+'/messages',{message_id:crypto.randomUUID(),text:message});addChat('我',message);addChat('临时伙伴',result.reply);$('message').value='';notice('临时讨论已保存，不计入正式画像');return}if(!sessionId)await startSession();const result=await api('/api/sessions/'+sessionId+'/messages',{text:message,attempt_id:crypto.randomUUID()});addChat('我',message);addChat('津津',result.reply);if(result.denial)notice(result.denial.rule+' · '+(result.denial.reason||'规则裁决'),true);$('message').value=''}
// The primary composer action is verification for a selected course task.
// Free discussion remains available through the explicit session action.
$('send').onclick=()=>{
  if (typeof activeContextId!=='undefined' && activeContextId) return $('session-submit').click();
  if (requestedCoursePending || !goalSupported) return notice('当前课程还在准备，请到计划页查看课程需求。',true);
  if (selected()) return $('submit').click();
  return run(()=>send($('message').value))();
};
$('message').addEventListener('keydown',event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();$('send').click()}});
async function loadReviews(preview=false){const request=++reviewListRequest;const horizon=preview?new Date(Date.now()+24*60*60*1000):null;const url='/api/learning/reviews/'+learner+(horizon?'?as_of='+encodeURIComponent(horizon.toISOString()):'');const data=await api(url);if(request!==reviewListRequest)return;const box=$('review-list');box.replaceChildren();$('review-scope').textContent=preview?'预览截至 '+horizon.toLocaleString()+' 预计到期的任务；时间与遗忘风险按预览时刻计算。预览不改变复习计划，到期前不能开始。':'仅显示当前已到期的复习任务。';if(!data.tasks.length){box.textContent=preview?'未来 24 小时暂无预计到期复习':'暂无到期复习';return}for(const task of data.tasks){const row=document.createElement('div');row.className='band';row.append(text('h3',task.kc_id),text('p','到期：'+new Date(task.due_at).toLocaleString()+' · '+(preview?'预览时的':'')+'遗忘风险 '+Math.round(task.forgetting_risk*100)+'%'));if(preview){row.append(text('p','预览任务 · 到期后刷新当前队列即可开始复习。'))}else{const btn=text('button','开始复习');btn.onclick=()=>{const a=assets.find(a=>a.kind==='delayed'&&a.kc_refs.some(k=>k.asset_id===task.kc_id));if(!a){notice('当前知识点缺少复习资产',true);return}if(![...$('assessment').options].some(o=>o.value===a.ref.asset_id)){const o=text('option',a.ref.asset_id+' · 到期复习');o.value=a.ref.asset_id;$('assessment').append(o)}$('assessment').value=a.ref.asset_id;chooseTask();review=task;$('assisted').checked=false;show('study');notice('到期复习已就绪')};row.append(btn)}box.append(row)}}
$('refresh-reviews').onclick=run(loadReviews);
$('preview-reviews').onclick=run(()=>loadReviews(true));
async function loadMetrics(){const result=await api('/api/learning/metrics/'+learner+'?kc_id='+encodeURIComponent($('target').value)+'&post_kind='+$('metric-kind').value);const el=$('metric-result');el.replaceChildren();if(result.status!=='comparable'){el.append(text('p',result.status==='incomparable'?'当前样本不可比较':'暂无可比较数据'),text('p','前测样本 '+result.pre_count+' · 对比样本 '+result.post_count));return}const band=document.createElement('div');band.className='metric';[['前测',result.pre_mean],['对比测',result.post_mean],['增量',result.gain]].forEach(([name,n])=>{const d=document.createElement('div');d.append(text('span',name),text('strong',Math.round(n*100)+'%'));band.append(d)});el.append(band,text('p','样本：'+result.pre_count+' / '+result.post_count+' · 描述性结果，课程资产尚未校准'));}
$('metric-kind').onchange=run(loadMetrics);
async function loadEvidence(){const [state,evidences]=await Promise.all([api('/api/learning/state/'+learner),api('/api/learning/evidence/'+learner)]);$('state-list').replaceChildren();if(!state.mastery.length)$('state-list').append(text('p','暂无学习状态'));state.mastery.forEach(m=>{const r=state.retention.find(r=>r.kc_id===m.kc_id);$('state-list').append(text('p',m.kc_id+' · 掌握估计 '+Math.round(m.p_mastery*100)+'% · 有效证据 '+m.effective_evidence_count+' · 保持版本 '+(r?.state_version||0)))});$('evidence-list').replaceChildren();if(!evidences.length)$('evidence-list').append(text('p','暂无学习证据'));[...evidences].reverse().forEach(e=>{const detail=document.createElement('details');detail.append(text('summary',e.assessment_id+' · '+(labels[e.verdict_status]||e.verdict_status)+' · '+new Date(e.occurred_at).toLocaleString()),text('pre',JSON.stringify(e,null,2)));$('evidence-list').append(detail)});await loadMetrics();await loadGrowth()}
$('refresh-evidence').onclick=run(loadEvidence);
$('refresh-development').onclick=run(async()=>{const selected=$('development-split').value;if(!selected)throw Error('请选择前后窗口的分界时间');const split=new Date(selected);if(!Number.isFinite(split.getTime())||split>=new Date())throw Error('分界时间必须早于当前时间');const result=await api('/api/learning/metrics/development/'+learner+'?split_at='+encodeURIComponent(split.toISOString()));const box=$('development-result');box.replaceChildren();const cognition=result.cognitive;box.append(text('h3','认知层级窗口'),text('p',cognition.status==='comparable'?'已取得可比较的认知层级证据':cognition.status==='incomparable'?'认知层级证据不可比较':'认知层级证据不足'),text('p','分界前 '+cognition.before_count+' 条 · 分界后 '+cognition.after_count+' 条'));if(cognition.status==='comparable')box.append(sourceDetails({before_distribution:cognition.before_distribution,after_distribution:cognition.after_distribution,rubric_version:cognition.rubric_version}));const autonomy=result.autonomy;box.append(text('h3','自主性行为'),text('p',autonomy.status==='insufficient_data'?'暂无行为数据':'独立尝试 '+autonomy.independent_attempt_count+' · 独立完成 '+autonomy.independent_success_count+' · 支架作答 '+autonomy.assisted_attempt_count),text('p','主动求助 '+autonomy.help_request_count+' · 自我检查 '+autonomy.self_check_count+' · 反思 '+autonomy.reflection_count+' · 修订 '+autonomy.revision_count),text('p','窗口与行为描述，不作因果效果结论或排名。'),sourceDetails(result.source_refs));notice('发展证据已更新')});
$('rebuild-memory').onclick=run(async()=>{const memory=await api('/api/learning/memory/'+learner+'/rebuild',{});const box=$('memory-result');box.replaceChildren(text('p','重建时间：'+new Date(memory.as_of).toLocaleString()),text('p','事实来源：'+memory.l1.evidence_refs.length+' 条学习证据、'+memory.l1.event_refs.length+' 条交互事件'));for(const session of memory.l2){const detail=document.createElement('details');detail.append(text('summary','会话 '+session.session_id+' · '+session.evidence_refs.length+' 条证据'),text('p','验证记录：'+Object.entries(session.verdict_counts).map(([key,value])=>(labels[key]||key)+' '+value).join('、')),sourceDetails({evidence:session.evidence_refs,events:session.event_refs}));box.append(detail)}box.append(text('p','长期描述只引用状态版本与行为来源。'),sourceDetails({l1:memory.l1,l3:memory.l3,view_id:memory.view_id}));notice('学习记忆已重建')});
run(async()=>{const config=await api('/api/learning/config');learner=config.learner_id;$('logout').hidden=!config.local_auth_enabled;$('identity').textContent='本地学习者';$('identity').title=learner;const data=await api('/api/learning/assets');assets=data.assessments;data.knowledge.forEach(k=>{const o=text('option',k.title);o.value=k.ref.asset_id;$('target').append(o)});$('target').value=data.knowledge.some(k=>k.ref.asset_id==='MATH.G7.EQ.SOLVE')?'MATH.G7.EQ.SOLVE':data.knowledge[0]?.ref.asset_id||'';changeTarget();if(!await loadConsent())show('settings');else{changeTarget();await restorePlanWorkspace();await restoreWorkspaceExtras();show('study')}})()
